networks:
  terabyte_bridge:
    name: terabyte_bridge
    driver: bridge

services:
  bot:
    container_name: terabyte_bot
    build: 
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    networks:
      - terabyte_bridge
    volumes:
      - ./terabyte.cfg.yml:/terabyte/terabyte.cfg.yml
    depends_on:
      database:
        condition: service_healthy

  database:
    container_name: terabyte_psql
    image: postgres:latest
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB} 
    volumes:
      - terabyte_psql:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - terabyte_bridge
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  terabyte_psql:
    name: terabyte_psql
    driver: local
